**data insights and data transformation

In [1]:
import numpy as np


In [3]:
prices=np.array([100,200,300,400,500])

In [4]:
prices*1.10

array([110., 220., 330., 440., 550.])

**broadcasting concept

In [5]:
prices+5

array([105, 205, 305, 405, 505])

In [9]:
arr=np.array([[100,200,300,400,500,56,43],[234,567,54,3,456,788,345]])

In [10]:
arr+5

array([[105, 205, 305, 405, 505,  61,  48],
       [239, 572,  59,   8, 461, 793, 350]])

**indexing and slicing

In [12]:
slicearr=np.array([100,200,300,400,500])

In [13]:
slicearr[1]

200

In [18]:
slicearr[1:4]

array([200, 300, 400])

In [19]:
matrix =np.array ([
    [1, 2, 3],
    [4, 5, 6]
])

In [20]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
matrix[0][1:]

array([2, 3])

In [23]:
matrix[1][0:2]

array([4, 5])

In [28]:
matrix[:,0]

array([1, 4])

In [27]:
matrix[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
matrix[0,0:]

array([1, 2, 3])

**scenaeraio  based questions 1

In [31]:
sales1=np.array([120,85,60])
sales2=np.array([150,95,75])

In [32]:
sales1+sales2

array([270, 180, 135])

In [33]:
growth = ((sales2 - sales1) / sales1) * 100
print(growth)

[25.         11.76470588 25.        ]


In [34]:
max(growth)

25.0

In [35]:
max_index = np.argmax(growth)

print("the product have higher growthis ",max_index)

the product have higher growthis  0


**scenaeraio  based questions 2

In [36]:
temps = np.array([
    [25, 28, 30],
    [22, 24, 26],
    [30, 32, 33],
    [27, 29, 31],
    [20, 21, 23]
])

In [38]:
temps*9//5+32

array([[77, 82, 86],
       [71, 75, 78],
       [86, 89, 91],
       [80, 84, 87],
       [68, 69, 73]])

**scenaeraio  based questions 3

In [39]:
bp = np.array([
    [120, 80],
    [135, 85],
    [140, 90],
    [110, 70],
    [125, 75]
])

In [41]:
#first coloumn
systolic = bp[:, 0]

In [42]:
systolic

array([120, 135, 140, 110, 125])

In [52]:
for c in systolic:
    if c>130:
        print(c)

135
140


In [53]:
bp[bp[:, 1] < 80, 1] = 80 #by slicing
print(bp)


[[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]


In [54]:
for i in range(len(bp)):
    if bp[i][1]<80:
        bp[i][1]=80

print(bp)
        

[[120  80]
 [135  85]
 [140  90]
 [110  80]
 [125  80]]


**scenaeraio  based questions 4

In [57]:
yields = np.array([
    [2.5, 3.0, 1.8],
    [2.8, 3.2, 2.0],
    [3.1, 2.9, 2.2],
    [2.6, 3.1, 1.9]
])

In [61]:
yields[1]+=np.array([0.2,0.3,0.1])

In [62]:
yields

array([[2.5, 3. , 1.8],
       [3. , 3.5, 2.1],
       [3.1, 2.9, 2.2],
       [2.6, 3.1, 1.9]])

In [63]:
yields[:-1]*=1.1

In [64]:
yields

array([[2.75, 3.3 , 1.98],
       [3.3 , 3.85, 2.31],
       [3.41, 3.19, 2.42],
       [2.6 , 3.1 , 1.9 ]])

In [65]:
for i in range(len(yields)): #multiply last column by 1.1
    yields[i][2]*=1.1

yields    

array([[2.75 , 3.3  , 2.178],
       [3.3  , 3.85 , 2.541],
       [3.41 , 3.19 , 2.662],
       [2.6  , 3.1  , 2.09 ]])

In [67]:
avg=np.mean(yields,axis=0)

In [68]:
avg

array([3.015  , 3.36   , 2.36775])

In [69]:
print("max yield of a product in single region is",np.argmax(avg))

max yield of a product in single region is 1


**scenaeraio  based questions 5

In [73]:
a=np.array([[1,2,3,4],
            [4,5,6,7]])
a[0:,0:2]

array([[1, 2],
       [4, 5]])

**boolean indexing    arrayname[condition]

In [74]:
a=np.array([23,56,78,65,78,34,23,65,78])

In [76]:
a[a>30]

array([56, 78, 65, 78, 34, 65, 78])

In [ ]:
# farm crop yield analysis rows = crops,coloumns=season
# Scenario: Farm Crop Yield Analysis
# A farm tracks the yield (in kilograms) of three different crops — Wheat, Rice, and Corn — across four seasons (Spring, Summer, Autumn, Winter).
# The farm manager wants to analyze the data to make better decisions for next year.
# Tasks
# - Create a 2D array representing crop yields for 3 crops across 4 seasons.
# - Rows = crops
# - Columns = seasons
# - Increase all yields by 10% to account for improved irrigation.
# - Extract only Wheat’s yields (the first crop).
# - Find the average yield per crop across all seasons.
# - Identify yields greater than 3000 kg (to see which crops/seasons performed exceptionally well).

In [86]:
crops=np.array([[20,30,40,55],[32,23,45,12],[34,67,89,32]])

In [87]:
crops

array([[20, 30, 40, 55],
       [32, 23, 45, 12],
       [34, 67, 89, 32]])

In [79]:
increased_yield=crops*1.10 #Increase all yields by 10% to account for improved irrigation.

In [81]:
increased_yield[0] #Extract only Wheat’s yields (the first crop).

array([22. , 33. , 44. , 60.5])

In [82]:
avg=np.mean(increased_yield,axis=1)

In [84]:
avg #Find the average yield per crop across all seasons.

array([39.875, 30.8  , 61.05 ])

In [85]:
increased_yield[increased_yield>30]

array([33. , 44. , 60.5, 35.2, 49.5, 37.4, 73.7, 97.9, 35.2])

In [89]:
increased_yield>30  #for seeinh crop that does exceptionally well

array([[False,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

**factory Scenario

In [95]:
production = np.array([
    [550, 590, 480, 570],   # Gadgets
    [400, 420, 450, 470],   # Tools
    [480, 510, 530, 550]    # Machines
])

In [96]:
production = production * 1.05
print(production)

[[577.5 619.5 504.  598.5]
 [420.  441.  472.5 493.5]
 [504.  535.5 556.5 577.5]]


In [97]:
gadgets = production[0]
print("Gadgets Production:", gadgets)

Gadgets Production: [577.5 619.5 504.  598.5]


In [98]:
avg_per_product = np.mean(production, axis=1)
print("Average per product:", avg_per_product)

Average per product: [574.875 456.75  543.375]


In [99]:
high_values = production[production > 500]
print("Production values > 500:", high_values)

Production values > 500: [577.5 619.5 504.  598.5 504.  535.5 556.5 577.5]
